submariner-io/admiral

pkg/federate/federator.go
pkg/federate/kubefed/resource.go

This patch changes the cluster names argument's name to clusterNames and
it also makes it an optional argument to make it a cleaner call when it
needs to distribute to all clusters.

Change Distribute interface to have optional arguments

---

go.mod
pkg/federate/kubefed/cluster.go
pkg/federate/kubefed/cluster_test.go
pkg/federate/kubefed/federator.go
pkg/federate/kubefed/resource.go
pkg/federate/kubefed/resource_test.go

Modified code that referenced components in the kubefed project to
eliminate the dependency. The kubefed code base we're referencing is
a bit old and uses old k8s et al libs which will prevent us from
bumping to new versions of those libs (eg controller-runtime).
Specific changes:
- Redefine some constants instead of getting them from kubefed
- Use the dymanic client and Unstructured APIs to avoid having to
reference the KubeFedCluster struct

Remove kubefed code dependency

---

go.mod
pkg/workqueue/queue.go

The idea here is to put reusable components into admiral to be used by submariner and lighthouse (and possibly others in the future). This avoids lighthouse having to depend on submariner and its release cadence. 
Another reusable component will be the generic datastoresyncer which will live in admiral.  This component will also want to use the workqueue wrapper - if we left it in submariner then we'd have a cross-dependency between the projects.

Move workqueue from submariner for reuse

---

scripts/validate

The bump to a new golangci-lint version is causing a timeout - need to bump
the timeout as was done in other projects.

Fix CI validate failure

---

pkg/syncer/broker/config.go
pkg/syncer/broker/syncer.go

The trust anchor stored in the broker information reflects the trust
chain of the token, not necessarily the trust chain of the API
endpoint; but we're using it for the latter in all cases.
This changes NewSyncer to check whether the clientset can be used,
by retrieving the first resource that's supposed to be synchronised.
This allows the configuration to be verified, and switched to use the
stored trust anchor if necessary.

Check whether the CA trust chain is needed

---

pkg/syncer/broker/federator.go
pkg/syncer/broker/federator_test.go
pkg/syncer/test/util.go

The broker Federator previously stripped out the "status" field to
avoid potential performance issues but lighthouse needs it synced.
Instead of automatically stripping it, we can defer to the TransformFunc
or add a flag to do it later if needed.

Federator should sync the "status" field

---

pkg/syncer/broker/syncer_test.go
pkg/syncer/resource_syncer.go
pkg/syncer/resource_syncer_test.go
test/e2e/syncer/broker.go

Lighthouse has a use case to have the operation - _Create_, _Update_, or _Delete_ - passed into the TransformFunc.

Add operation param to syncer TransformFunc

---

pkg/syncer/broker/syncer.go
pkg/syncer/broker/syncer_test.go

Previously it created a remote and local federators per resource syncer and stored the remote federators per resource type. However a federator isn't specific to a resource type so we can create singleton instances and reuse for each syncer.

Create singleton federators in broker syncer

---

pkg/syncer/broker/syncer.go
pkg/syncer/broker/syncer_test.go
pkg/syncer/test/util.go

Users to be able to construct a broker syncer with fake clients for UTs. There is a non-exported `newSyncer` function used by the local UTs so export it. This enables the local syncer UTs to be moved to the test package.
Also added some more UT utilities.

Add exported broker syncer constructor for UTs

---

pkg/fake/dynamic_client.go
pkg/syncer/broker/syncer.go

We need to expose the `OnSuccessfulSync`  via the broker syncer API. This was overlooked when it was originally added.
Also a minor addition to the fake `DynamicResourceClient`. These will both go into the next pre-release for lighthouse.

Expose the OnSuccessfulSync via the broker syncer

---

.golangci.yml
pkg/gomega/matchers.go

Both linters flag the same dot imports in this repo, so fixing one fixes both.
Builds on https://github.com/submariner-io/admiral/pull/87.

Enable golint and stylecheck linting, fix errors

---

.markdownlint.yml
README.md

Configure custom maximum line length of 140 chars to match Go linting.
Will be tested by the verify job once it's update in Shipyard.
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

Fix MD lint violations

---

test/e2e/deploy/crds.yaml

The apiextensions.k8s.io/v1beta1 version of CustomResourceDefinition
is deprecated in Kubernetes v1.16 and will no longer be served in
v1.19. Use apiextensions.k8s.io/v1 instead.
Signed-off-by: Stephen Kitt <skitt@redhat.com>

Migrate CRDs to apiextensions v1

---

pkg/fake/failing_reactor.go

The generated fake client sets allow for Reactors to hook in to
intercept and handle CRUD operations. This adds a generic FailingReactor
that allows mock errors to be returned from CRUD operations.

Add hook to mock CRUD errors in fake client sets

---

pkg/fake/delete_colection_reactor.go

The generated fake client set code doesn't implement DeleteCollection so add a Reactor to do it.

Add DeleteCollection Reactor

---

pkg/federate/federator.go

A `Federator` implementation that does nothing. This will be useful for syncers that only watch resources and don't actually sync anything.

Add NoopFederator

---

pkg/syncer/broker/federator.go
pkg/syncer/broker/federator_test.go
pkg/syncer/test/util.go

There are cases where additional fields need to be preserved so make it configurable. An example is `OwnerReferences` when syncing local -> local.

Make metadata fields to preserve configurable in broker Federator

---

pkg/fake/dynamic_client.go
pkg/syncer/broker/federator_test.go
pkg/syncer/broker/syncer_test.go

Tests usually need to create their own Scheme to avoid race conditions with the shared Scheme.

Pass Scheme to NewDynamicClient

---

pkg/syncer/resource_syncer.go
pkg/watcher/resource_watcher.go
pkg/watcher/resource_watcher_test.go
pkg/watcher/watcher_suite_test.go

The resource syncer can be used to simply watch resources to eliminate the boilerplate of using informers directly. Added a wrapper with a simpler interface for this purpose.

Add resource watcher wrapper

---

pkg/watcher/resource_watcher.go
pkg/watcher/resource_watcher_test.go

The following fields have been moved to ResourceConfig
* SourceNamespace
* SourceLabelSelector
* SourceFieldSelector
in a way that multiple resources can be watched from different
namespaces, and with different selectors.
Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

Make the resource watcher selectors resource specific

---

pkg/watcher/resource_watcher.go
pkg/watcher/resource_watcher_test.go

We need to capture` rc.Handler` in a closure var within the loop otherwise the next iteration overwrites `rc` and the function passed to the `ResourceSyncer` observes the incorrect handler.
Also moved the Name field to the `ResourceConfig`.

Fix bug in the resource watcher

---

pkg/watcher/resource_watcher.go
pkg/watcher/resource_watcher_test.go
test/e2e/e2e_test.go
test/e2e/syncer/broker.go
test/e2e/util/util.go
test/e2e/watcher/watcher.go

Watcher now accepts a dynclien and restmapper in the Config structure
as optional parameters.
Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

Make watcher more testable from consumer projects

---

pkg/log/loglevels.go
pkg/syncer/broker/federator.go
pkg/syncer/resource_syncer.go
pkg/util/create_or_update.go
pkg/workqueue/queue.go

Some of the admiral syncer libraries are extra-verbose and while
they would be helpful in multiple situations during normal debugging
can produce a cumbersome amount of logs.
Two extra levels of logging have been created for admiral: LIBDEBUG
and LIBTRACE.
Also, some object dumping log entries have been moved into LIBTRACE too.
Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

Separate admiral logs from lib-consumer logs, and sanitize levels

---

.markdownlinkcheck.json
README.md

Also ignore GH badges in MD link checks. Link linting sometimes incorrectly fails on GitHub CI badge URLs.

Add CI badges to README
