submariner-io/admiral

pkg/federate/kubefed/cluster.go, pkg/federate/kubefed/cluster_test.go, pkg/federate/kubefed/federator.go
=> Use k8s workqueue instead of chan for clusterWatcher

go.mod, pkg/federate/kubefed/federator.go, pkg/federate/kubefed/resource.go, pkg/federate/kubefed/resource_test.go
This patch implements the Distribute operation for the KubeFed backend.
=> Adding Distribute operation for KubeFed backend

pkg/federate/kubefed/resource.go, pkg/federate/kubefed/resource_test.go
Reverts submariner-io/admiral#11
=> Revert "Nits/distribute"

.travis.yml
Separate ci into multiple stages.
=> Multi stage ci build

pkg/federate/kubefed/resource.go, pkg/federate/kubefed/resource_test.go
For update, a valid ResourceVersion must be specified. The API server/etcd
uses optimistic locking via CAS with the ResourceVersion, ie the input
ResourceVersion must match the existing ResourceVersion on update. The pattern
is to get the existing resource, modify it as needed but retain the ResourceVersion,
then issue the update. There's also a utility, retry.RetryOnConflict, to aid with
retries in case of a conflict due to a concurrent modification.
Also added some debug logging and more context to the error messages to aid
in troubleshooting.
=> Fix update issue in kubefed Distribute

pkg/log/loglevels.go
=> Move log levels from submariner for reuse

go.mod, go.sum, pkg/fake/dynamic_client.go, pkg/federate/federator.go, pkg/syncer/broker/broker_suite_test.go, pkg/syncer/broker/config.go, pkg/syncer/broker/federator.go, pkg/syncer/broker/federator_test.go, pkg/syncer/broker/utils.go, pkg/syncer/test/util.go, pkg/util/util.go
=> Add broker Federator implementation

pkg/syncer/resource_syncer_test.go
=> Fix race failure in resource_syncer_test

.github/workflows/validations.yaml
=> Add validations as GH actions

pkg/federate/fake/federator.go, pkg/syncer/broker/syncer_test.go, pkg/syncer/resource_syncer.go, pkg/syncer/resource_syncer_test.go, test/e2e/syncer/broker.go
See https://github.com/submariner-io/admiral/issues/67 for use case.
Added a boolean return value from the TransformFunc to specify to
re-queue/retry.
=> Add option to re-queue from TransformFunc

Dockerfile.dapper, go.mod, go.sum
=> Update to v0.5.0

.golangci.yml, pkg/syncer/test/util.go
Builds on https://github.com/submariner-io/admiral/pull/87.
=> Enable gofmt linting, fix error

.golangci.yml, pkg/syncer/broker/federator.go, pkg/syncer/resource_syncer.go, pkg/syncer/test/util.go, test/e2e/syncer/broker.go
=> Enable gocritic style linting, fix errors

.golangci.yml, pkg/fake/dynamic_client.go, pkg/syncer/broker/federator.go, pkg/syncer/broker/federator_test.go, pkg/syncer/broker/syncer.go, pkg/util/helpers.go, test/e2e/syncer/broker.go
Builds on https://github.com/submariner-io/admiral/pull/87.
=> Enable lll line length linting, fix errors

pkg/federate/fake/federator.go, pkg/syncer/resource_syncer.go, pkg/syncer/resource_syncer_test.go, pkg/syncer/syncer.go
=> Add callback on successful sync

.golangci.yml, pkg/fake/dynamic_client.go, pkg/federate/fake/federator.go, pkg/gomega/matchers.go, pkg/syncer/broker/syncer.go, pkg/syncer/resource_syncer.go, pkg/syncer/test/util.go, pkg/util/create_or_update.go, test/apis/admiral.submariner.io/v1/register.go, test/e2e/syncer/broker.go
Builds on https://github.com/submariner-io/admiral/pull/87.
=> Enable wsl positive whitespace linter, fix errors

pkg/syncer/resource_syncer.go, pkg/syncer/resource_syncer_test.go
There aee use cases for syncing Status changes,
=> Don't suppress update on Status change

pkg/syncer/broker/syncer.go, pkg/syncer/broker/syncer_test.go, pkg/syncer/resource_syncer.go, pkg/syncer/resource_syncer_test.go, pkg/syncer/test/util.go
Also added a flag to make it configurable.
=> Ignore Status updates by default

pkg/syncer/broker/syncer.go, pkg/syncer/broker/syncer_test.go, pkg/syncer/resource_syncer.go, pkg/syncer/resource_syncer_test.go, pkg/util/helpers.go
This replaces the ProcessStatusUpdates flag providing more flexibility.
=> Add function hook to compare resources on update

Dockerfile.dapper, go.mod, go.sum
This releases admiral as 0.6.0 for future import in the
other Submariner projects
=> Bump and pin shipyard to 0.6.0

.github/workflows/dco-check.yml, .github/workflows/e2e.yml, .github/workflows/md-links-periodic.yml, .github/workflows/md-links.yml, .github/workflows/validations.yml, .github/workflows/yaml-lint.yml, .golangci.yml, .markdownlint.yml, .yamllint.yml, test/e2e/deploy/crds.yaml
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>
=> Add YAML linting, fix errors

pkg/syncer/broker/syncer.go, pkg/syncer/broker/syncer_test.go, pkg/syncer/resource_syncer.go, pkg/syncer/resource_syncer_test.go, pkg/syncer/syncer.go
See https://github.com/submariner-io/admiral/issues/115
=> Add method to get cached resource from syncer

pkg/syncer/broker/federator.go, pkg/syncer/broker/federator_test.go
Previously the Federator always used the given target namespace for creating/deleting all resources. Now if the target namespace is empty (meaning all), it will use the source resource's namespace.
=> Allow per-resource namespace in the Federator

CODEOWNERS
Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>
=> Make CODEOWNERS additive

pkg/syncer/broker/syncer.go, pkg/syncer/broker/syncer_test.go, pkg/syncer/resource_syncer.go
For _broker -> local_ we don't want to `WaitForCacheSync` in case the broker isn't available on startup.
=> Make WaitForCacheSync in syncer configurable

CODEOWNERS, CODEOWNERS.in
Following https://groups.google.com/u/1/g/submariner-dev/c/1lAmi0IwDgc
Signed-off-by: Stephen Kitt <skitt@redhat.com>
=> Generate CODEOWNERS, make myself an overall owner

pkg/syncer/broker/syncer.go
=> Add GetLocalFederator to ResourceSyncer

pkg/syncer/broker/syncer.go
`getCheckedBrokerClientset` is called on startup to check permissions access to the broker API server. The downside is that it will also return an error if the broker isn't available and other possible transient failures. This results in the calling process exiting which may not be desirable. So this check was adjusted to only return for an authorization error and proceed for other errors.
Also changed the API call from `List` to `Get` as the former may incur significantly more overhead. We expect the `Get` to fail with `IsNotFound` which is OK.
=> Adjust broker client check

pkg/syncer/resource_syncer.go, pkg/util/helpers.go
- Removed unnecessary logging
- Reduced output for some
- Added more context to some
=> Syncer logging changes

.github/workflows/codeowners.yml, CODEOWNERS.in
See commit messages for details.
=>  Add CI for CODEOWNERS generation

.github/workflows/periodic_e2e.yml, .github/workflows/periodic_linting.yml
See commit messages for details.
=> Add periodic E2E tests to find flaky failures

pkg/stringset/stringset.go, pkg/stringset/stringset_test.go
Initial code copied from submariner with the addition of an unsynchronized version.
=> Add String Set

CONTRIBUTING.md
Signed-off-by: nyechiel <nyechiel@redhat.com>
=> Fix broken URL in CONTRIBUTING.md

pkg/stringset/stringset.go, pkg/stringset/stringset_test.go
Allow initial strings on creation and new `AddAll` function for convenience.
=> Populate StringSet on creation

pkg/syncer/broker/syncer_test.go, pkg/syncer/resource_syncer.go, pkg/syncer/resource_syncer_test.go, pkg/watcher/resource_watcher.go, pkg/watcher/resource_watcher_test.go, pkg/workqueue/queue.go, test/e2e/syncer/broker.go, test/e2e/watcher/watcher.go
Users may need this info in callbacks.
=> Expose numRequeues from resoure syncer/watcher

pkg/syncer/broker/syncer.go, pkg/syncer/broker/syncer_test.go
Add optional detail fields to the `Config` in lieu of the `NewWithDetails` function.
=> Simplify broker syncer creation for unit tests
